[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "always" 