name: aura-farming-video
services:
- name: web
  source_dir: /
  github:
    repo: FactualTechAthereusUS/pixelremoversss
    branch: main
    deploy_on_push: true
  run_command: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --browser.gatherUsageStats=false
  environment_slug: python
  instance_count: 1
  instance_size_slug: professional-s
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: PLATFORM
    value: digitalocean

# Professional-S: $24/month (2GB RAM, 1 vCPU) - Recommended for video processing
# Can handle 200MB+ video files reliably